# brightnessctl
# Autogenerated from man page /usr/share/man/man1/brightnessctl.1.gz
complete -c brightnessctl -s h -l help --description '.'
complete -c brightnessctl -s l -l list --description '.'
complete -c brightnessctl -s q -l quiet --description '.'
complete -c brightnessctl -s p -l pretend --description '.'
complete -c brightnessctl -s m -l machine-readable --description '.'
complete -c brightnessctl -s n -l min-value --description '.'
complete -c brightnessctl -s e -l exponent --description '.'
complete -c brightnessctl -s s -l save --description '.'
complete -c brightnessctl -s r -l restore --description '.'
complete -c brightnessctl -s d -l device --description '.'
complete -c brightnessctl -s c -l class --description '.'
complete -c brightnessctl -s v -l version --description '.'

